version: '3.9'
services:
  quiz:
    build: .
    container_name: quiz_app
    image: 1597846/quiz:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Quiz
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
  postgres:
    container_name: quiz_postgres
    image: postgres
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - quiz-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "Quiz"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
volumes:
  quiz-data:
