version: '3.9'
services:
  quiz:
    build: .
    container_name: quiz
    image: quiz:latest
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "quiz"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      ports:
        - "5432:5432"
